[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
protobuf = "^5.28.3"
grpcio = "^1.67.1"

[tool.poetry.group.dev.dependencies]
grpcio-tools = "^1.67.1"

[tool.poetry.group.lint.dependencies]
grpc-stubs = "^1.53.0.5"
